export enum PhonenumberType {
  OFFICE_PRIMARY = 'OFFICE_PRIMARY',

  OFFICE_SECONDARY = 'OFFICE_SECONDARY',

  OFFICIAL_NUMBER1 = 'OFFICIAL_NUMBER1',

  OFFICIAL_NUMBER2 = 'OFFICIAL_NUMBER2',

  PERSONAL_PRIMARY = 'PERSONAL_PRIMARY',

  PERSONAL_SECONDARY = 'PERSONAL_SECONDARY',

  EMERYGENCY1 = 'EMERYGENCY1',

  EMERYGENCY2 = 'EMERYGENCY2',

  WHATSAPP1 = 'WHATSAPP1',

  WHATSAPP2 = 'WHATSAPP2',
}
